feature: add pages
kuanyshtokanov/startupjs_rps pull request #1
Opened 2021-04-06 14:13 UTC by kuanyshtokanov

2021-04-15 12:56 UTC, ssstelsss requested changes

2021-04-15 12:56 UTC, ssstelsss commented on components/GameForm/index.js
> +    await model.add('games', {
давай вынесем это в модель коллекции games. А здесь уже будем просто вызывать метод коллекции.

посмотри везде

2021-04-15 12:56 UTC, ssstelsss commented on components/GameForm/index.js
> +    await model.add('rounds', {
то же самое

2021-04-15 12:56 UTC, ssstelsss commented on components/GameForm/index.js
> +        Input.gameInput(
здесь хватит простого TextInput из @startupjs/ui
Input это обертка для более сложных конструкций

2021-04-15 12:56 UTC, ssstelsss commented on components/GamesList/index.js
> +  const handleAddGame = () => emit('url', '/createGame')
не используется

2021-04-15 12:56 UTC, ssstelsss commented on components/GamesListItem/index.js
> +  const [curGame, $curGame] = useDoc('games', game._id)
а что у тебя прилетает в game? Думаю имеет смысл прокинуть сюда только gemeId и потом здесь подписаться const [game, $game] = useDoc('games', gameId)

а то выходит что у тебя curGame и  game одно и тоже

2021-04-15 12:56 UTC, ssstelsss commented on components/Leaderboard/index.js
> +          Span.name= player.name
придерживайся одного стиля везде либо через =, либо через #{}

2021-04-15 12:56 UTC, ssstelsss commented on components/Leaderboard/index.styl
> +  // width 480px
лишнее

2021-04-15 12:56 UTC, ssstelsss commented on components/Login/index.js
> +        label="Professor"
придерживайся одного стиля везде либо "string", либо 'string'

2021-04-15 12:56 UTC, ssstelsss commented on components/RoundChronology/index.styl
> +  // flex-direction row
не нужно

2021-04-15 12:56 UTC, ssstelsss commented on components/RoundChronology/index.styl
> +  // flex-direction row
почисти везде коменты

2021-04-15 12:56 UTC, ssstelsss commented on components/RoundChronology/index.styl
> +  width 200px
используй u

2021-04-15 12:56 UTC, ssstelsss commented on main/Layout/index.js
> +  const [user] = useDoc('users', userId)
можно сразу взять юзера из сессии const [user, $user] = useSession('user')

2021-04-15 12:56 UTC, ssstelsss commented on main/pages/PGame/Player/index.js
> +  const currentRound = curRounds[0]
думаю имеет смысл использовать useQueryDoc если тебе нужен только один документ

2021-04-15 12:56 UTC, ssstelsss commented on main/pages/PGame/Professor/index.js
> +  const [curRounds, $curRounds] = useQuery('rounds', {
тоже самое используй useQueryDoc

2021-04-15 13:08 UTC, ssstelsss commented
![image](https://user-images.githubusercontent.com/58818714/114874252-d2492980-9e04-11eb-8417-a0f8fa1ebedb.png)
на андроиде нельзя ввести текст

2021-04-16 10:56 UTC, kuanyshtokanov commented on components/GamesListItem/index.js
> +  const [curGame, $curGame] = useDoc('games', game._id)
сюда мне прилетает 'game', которая пришла из useQuery со всеми полями как например '_m.ctime', которое я использую в отображении, я не стал добавлять новое поле в модель 'games' для даты и использую стандартное '_m.ctime'
поэтому здесь подписываюсь на коллекцию чтобы потом делать свои нужные модификации

2021-04-16 10:56 UTC, kuanyshtokanov commented on components/GamesListItem/index.js
> +  const [curGame, $curGame] = useDoc('games', game._id)
я бы мог здесь использовать useQueryDoc, но он мне не даст '_m.ctime'

2021-04-16 12:57 UTC, ssstelsss commented on components/GamesListItem/index.js
> +  const [curGame, $curGame] = useDoc('games', game._id)
лучше не использовать эти поля

2021-04-19 13:24 UTC, ssstelsss commented on main/pages/PGame/Professor/index.js
> +      id: rId,
id лучше в моделе инитить

2021-04-19 13:25 UTC, ssstelsss approved these changes

2021-04-28 13:22 UTC, merged